FROM vllm/vllm-openai:v0.22.1
COPY machete_rtn.py /usr/local/lib/python3.12/dist-packages/machete_rtn.py
RUN echo "" >> /usr/local/lib/python3.12/dist-packages/vllm/__init__.py && \
    echo "try:" >> /usr/local/lib/python3.12/dist-packages/vllm/__init__.py && \
    echo "    import machete_rtn" >> /usr/local/lib/python3.12/dist-packages/vllm/__init__.py && \
    echo "except Exception as _e:" >> /usr/local/lib/python3.12/dist-packages/vllm/__init__.py && \
    echo "    print('machete_rtn import err', _e)" >> /usr/local/lib/python3.12/dist-packages/vllm/__init__.py
